name: SkylaskInvsee
version: ${project.version}
main: me.ialistannen.skylaskinvsee.SkylaskInvsee
depend: [PerceiveCore]
authors: [I_Al_Istannen]
description: A small plugin to allow you to view another player's inventory
